[package]
name = "cainam-core"
version = "0.1.0"
edition = "2021"
authors = ["Matt Gunnin <matt@cainamventures.com>"]
repository = "https://github.com/cainamventures/cainam-core"
readme = "README.md"
keywords = ["ai", "solana", "rust", "cainam", "cainam-ventures"]
description = "Core functionality for the Cainam project"

[[bin]]
name = "autonomous-trader"
path = "cainam-trader/examples/autonomous_trader.rs"

[workspace]
resolver = "2"
members = [
    # plugins
    "plugins/birdeye",
    "plugins/discord",
    "plugins/twitter",
]
exclude = [
    "examples",
    "memory-bank",
    "migrations",
    "phases_output",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = "z"

[profile.release]
lto = "thin"
strip = true
codegen-units = 1
opt-level = "z"

[dependencies]
rig-core = "0.7.0"
rig-mongodb = "0.2.3"
anyhow = "1.0"
chrono = "0.4"
bigdecimal = { version = "0.2", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
bson = "2.0"
mockall = "0.11.0"
reqwest = { version = "0.11", features = ["json"] }