[package]
name = "pumpfun"
version.workspace = true
edition.workspace = true

[dependencies]
solagent-core = "0.1.3"
solagent-plugin-pumpfun = "0.1.0"
tokio = { version = "1.42.0", features = ["full"] }
