[package]
name = "token_security"
version.workspace = true
edition.workspace = true

[dependencies]
solagent-core = "0.1.3"
solagent-plugin-goplus = "0.1.0"
tokio = { version = "1.42.0", features = ["full"] }
