[package]
name = "gibwork"
version.workspace = true
edition.workspace = true

[dependencies]
solagent-core = "0.1.3"
solagent-plugin-gibwork = "0.1.1"
tokio = { version = "1.42.0", features = ["full"] }
