[package]
name = "get_balance"
version = "0.1.0"
edition = "2021"

[dependencies]
solagent-core = { path = "../../solagent-core" }
solagent-plugin-solana = { path = "../../solagent-plugins/solana" }
tokio = { version = "1.42.0", features = ["full"] }
